name: CI

on: [push, pull_request]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: VSCE package
        run: npm run package

  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node_version: "24"
      - name: Install dependencies
        run: npm install
      - name: Run eslint
        run: npm run lint

  grammar-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node_version: "24"
      - name: Install dependencies
        run: npm install
      - name: Run grammar tests
        run: npm run test:grammar
