name: Docs CI

on: [push, pull_request]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm install
      - name: Check readme linting
        run: npm run lint:md
